image:
    file: gitpod.dockerfile
tasks:
    - init: . ${GITPOD_REPO_ROOT}/gitpod.tasks.sh
ports:
    - port: 80
    - port: 8000
    - port: 8080
    - port: 3000
    #live-reload ports
    - port: 35729
    - port: 3001